import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ReactQueryProvider from "@/providers/reactQueryProvider";
import "./globals.css";

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import AppSidebar from "@/components/sidebar/SideBar";

import { Bounce, ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          <SidebarProvider>
            <AppSidebar />

            <main className="flex-1 w-full">
              <div className="p-4 min-[1100px]:hidden flex items-center border-b">
                
                <SidebarTrigger variant={"default"} className="w-20 bg-my-primary"/>
              </div>
              <ToastContainer
                position="top-right"
                autoClose={10000}
                pauseOnHover={true}
                draggable={true}
                theme={"colored"}
                transition={Bounce}
              />
              <div className="w-full px-4">{children}</div>
            </main>
          </SidebarProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
