import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ReactQueryProvider from "@/providers/reactQueryProvider";
import "./globals.css";

import AppSidebar from "@/components/sidebar/SideBar";

import { Bounce, ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          <div className="flex h-[1000] overflow-hidden">

            <AppSidebar />
            <main className="flex-1 w-full">
              <ToastContainer
                position="top-right"
                autoClose={10000}
                pauseOnHover={true}
                draggable={true}
                theme={"colored"}
                transition={Bounce}
              />
              <div className="w-full px-4">{children}</div>
            </main>
          </div>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
